### ISSUE TITLE
Marker props not working

### ISSUE THREAD

**Issue by stebogit** [rowanwins/leaflet-simplestyle#2]
Hey @rowanwins this nice little pugin is exactly what I was looking for to include in [turf-sandbox](https://turf-sandbox.herokuapp.com/)! So glad I found it! 😄 

I noticed though the marker styles are not included, any plan to add them?

**Comment by rowanwins** [comment]
Ha, glad you found it!

We should support marker styling - TBH I don't think I even checked when I wrote the plugin. I'll take a looksee and report back.

**Comment by stebogit** [comment]
Looks like this is the missing piece: https://github.com/mapbox/mapbox.js/blob/publisher-production/src/marker.js

**Comment by rowanwins** [comment]
Was just looking in the same repo - thanks for the pointer :)

**Comment by rowanwins** [comment]
So I've kind of got it working - the one thing I'm unhappy with at the moment is that I don't seem to be able to toggle back to the default marker yet as per what i can do with the `discardSimpleStyle` method on other layers

<img width="630" alt="Screen" src="https://user-images.githubusercontent.com/6735870/77845944-5c285380-71fe-11ea-9c46-5c5bac5f252f.png">

**Comment by stebogit** [comment]
😄 #3

**Comment by rowanwins** [comment]
Haha yah just saw that. I'll put up my PR and we can compare approaches

**Comment by stebogit** [comment]
Great!
But it's 3am here, so I'll take a look in a few hours 😜

**Comment by rowanwins** [comment]
Published as v1.2.1 to npm
