### ISSUE TITLE
Wrong protocol in iframe

### ISSUE THREAD

**Issue by stebogit** [rowanwins/leaflet-simplestyle#6]
I'm [rendering the map in an iframe](https://github.com/stebogit/turf-sandbox/blob/master/client/src/components/Output.js#L12-L15) passing to the src a base64 encoded string, which I think is the reason why the `iconUrl`'s protocol results in `data:` and I get this loading error:

![Screen Shot 2020-04-12 at 12 43 22 AM](https://user-images.githubusercontent.com/12717225/79063534-2439fb00-7c57-11ea-803d-68fc52ec15f3.png)

Am I doing it wrong?

**Comment by rowanwins** [comment]
Fixed in v1.2.2 :)

**Comment by rowanwins** [comment]
Hadn't thought of that scenario but the logic should now be more robust.

**Comment by stebogit** [comment]
I think the [latest version](https://unpkg.com/leaflet-simplestyle@1.2.2/dist/leaflet-simplestyle.min.js) was not published correctly:

![Screen Shot 2020-04-12 at 2 09 54 AM](https://user-images.githubusercontent.com/12717225/79065139-c7444200-7c62-11ea-8541-5831e3d8ef46.png)

**Comment by rowanwins** [comment]
Try v1.2.3

**Comment by stebogit** [comment]
YAY! 🎉 
Thanks @rowanwins!!
